import { FunctionComponent } from "react";
import ResourcesMenuContentCards from "./ResourcesMenuContentCards";
import styles from "./ResourcesMenuContentCollection.module.css";

export type ResourcesMenuContentCollectionType = {
  className?: string;
};

const ResourcesMenuContentCollection: FunctionComponent<
  ResourcesMenuContentCollectionType
> = ({ className = "" }) => {
  return (
    <div className={[styles.frame, className].join(" ")}>
      <ResourcesMenuContentCards
        byMaiSakurajimaSenpai="By Mai Sakurajima"
        unlockingTheFutureOfHealt="Unlocking the Future of Healthcare: How AI is Changing the Game"
        monotoneAdd="/monotone-add-17.svg"
      />
      <ResourcesMenuContentCards
        byMaiSakurajimaSenpai="By Marcus Aurelius"
        unlockingTheFutureOfHealt="How AI is Changing Personalized Health AI: Your Path to Well-Being Game"
        monotoneAdd="/monotone-add-17.svg"
        propBackgroundColor="#fff"
        propBoxShadow="unset"
        propOverflow="unset"
        metaFlagsPadding="var(--padding-54xl) 0px 0px"
        propColor="#242e49"
        propColor1="#5d6a85"
        propBackgroundColor1="1px solid #bec5d2"
        propColor2="#5d6a85"
        propDisplay="unset"
        propMinWidth="unset"
        propBackgroundColor2="1px solid #bec5d2"
        propColor3="#5d6a85"
        propColor4="#242e49"
        propAlignSelf="stretch"
        propBackgroundColor3="#edf5ff"
        propColor5="#0f67fe"
        propBackgroundColor4="#edf5ff"
        propColor6="#0f67fe"
        propBackgroundColor5="#edf5ff"
        propColor7="#0f67fe"
        blogActionsHeight="114px"
        blogActionsPadding="var(--padding-31xl) 0px 0px"
        propBackgroundColor6="#f2f5f9"
        propBorder="unset"
      />
      <ResourcesMenuContentCards
        byMaiSakurajimaSenpai="By Nero the Great"
        unlockingTheFutureOfHealt="The Power of Predictive Health: Staying One Step Ahead"
        monotoneAdd="/monotone-add-33.svg"
        propBackgroundColor="#0f67fe"
        propBoxShadow="0px 0px 0px 4px rgba(15, 103, 254, 0.25)"
        propOverflow="hidden"
        metaFlagsPadding="var(--padding-54xl) 0px 0px"
        propColor="#fff"
        propColor1="#fff"
        propBackgroundColor1="#a6cbff"
        propColor2="#fff"
        propDisplay="unset"
        propMinWidth="unset"
        propBackgroundColor2="#a6cbff"
        propColor3="#fff"
        propColor4="#fff"
        propAlignSelf="stretch"
        propBackgroundColor3="#458cff"
        propColor5="#fff"
        propBackgroundColor4="#458cff"
        propColor6="#fff"
        propBackgroundColor5="#458cff"
        propColor7="#fff"
        blogActionsHeight="114px"
        blogActionsPadding="var(--padding-31xl) 0px 0px"
        propBackgroundColor6="#fff"
        propBorder="1px solid var(--asklepios-gray-white)"
      />
      <ResourcesMenuContentCards
        byMaiSakurajimaSenpai="By Lucas Seneca"
        unlockingTheFutureOfHealt="Navigating Your Health Journey with DocPlus: A User Guideuture of Healthcare: How AI is Changing the Game"
        monotoneAdd="/monotone-add-17.svg"
        propBackgroundColor="#fff"
        propBoxShadow="unset"
        propOverflow="unset"
        metaFlagsPadding="var(--padding-70xl) 0px 0px"
        propColor="#242e49"
        propColor1="#5d6a85"
        propBackgroundColor1="1px solid #bec5d2"
        propColor2="#5d6a85"
        propDisplay="inline-block"
        propMinWidth="127px"
        propBackgroundColor2="1px solid #bec5d2"
        propColor3="#5d6a85"
        propColor4="#242e49"
        propAlignSelf="stretch"
        propBackgroundColor3="#edf5ff"
        propColor5="#0f67fe"
        propBackgroundColor4="#edf5ff"
        propColor6="#0f67fe"
        propBackgroundColor5="#edf5ff"
        propColor7="#0f67fe"
        blogActionsHeight="130px"
        blogActionsPadding="var(--padding-47xl) 0px 0px"
        propBackgroundColor6="#f2f5f9"
        propBorder="unset"
      />
      <ResourcesMenuContentCards
        byMaiSakurajimaSenpai="By Makima Smith"
        unlockingTheFutureOfHealt="AI in Healthcare: Transforming Patient Experience"
        monotoneAdd="/monotone-add-17.svg"
        propBackgroundColor="#fff"
        propBoxShadow="unset"
        propOverflow="unset"
        metaFlagsPadding="var(--padding-38xl) 0px 0px"
        propColor="#242e49"
        propColor1="#5d6a85"
        propBackgroundColor1="1px solid #bec5d2"
        propColor2="#5d6a85"
        propDisplay="inline-block"
        propMinWidth="129px"
        propBackgroundColor2="1px solid #bec5d2"
        propColor3="#5d6a85"
        propColor4="#242e49"
        propAlignSelf="unset"
        propBackgroundColor3="#edf5ff"
        propColor5="#0f67fe"
        propBackgroundColor4="#edf5ff"
        propColor6="#0f67fe"
        propBackgroundColor5="#edf5ff"
        propColor7="#0f67fe"
        blogActionsHeight="98px"
        blogActionsPadding="var(--padding-15xl) 0px 0px"
        propBackgroundColor6="#f2f5f9"
        propBorder="unset"
      />
      <ResourcesMenuContentCards
        byMaiSakurajimaSenpai="By Megumin Taylor"
        unlockingTheFutureOfHealt="From Data to Insights: The Science of Healthcare Analytics for Everyone"
        monotoneAdd="/monotone-add-17.svg"
        propBackgroundColor="#fff"
        propBoxShadow="unset"
        propOverflow="unset"
        metaFlagsPadding="var(--padding-54xl) 0px 0px"
        propColor="#242e49"
        propColor1="#5d6a85"
        propBackgroundColor1="1px solid #bec5d2"
        propColor2="#5d6a85"
        propDisplay="unset"
        propMinWidth="unset"
        propBackgroundColor2="1px solid #bec5d2"
        propColor3="#5d6a85"
        propColor4="#242e49"
        propAlignSelf="stretch"
        propBackgroundColor3="#edf5ff"
        propColor5="#0f67fe"
        propBackgroundColor4="#edf5ff"
        propColor6="#0f67fe"
        propBackgroundColor5="#edf5ff"
        propColor7="#0f67fe"
        blogActionsHeight="114px"
        blogActionsPadding="var(--padding-31xl) 0px 0px"
        propBackgroundColor6="#f2f5f9"
        propBorder="unset"
      />
    </div>
  );
};

export default ResourcesMenuContentCollection;
